# TUGAS 3: UJICOBA COSINUS SIMILARITY PYTHON

Nama : MOHAMMAD IQBAL SURYA RAMADHAN

NIM  : 210411100002

KELAS: TKI - B

cosim_210411100002_2

# Cosinus Similatarity dengan python

In [ ]:
from google.colab import drive 
drive.mount ('/content/drive')

Mounted at /content/drive


In [ ]:
pip install Sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 KB 5.5 MB/s eta 0:00:00


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import re

In [ ]:
REGEX = re.compile(r"\s")
def tokenize(text):
    return [tok.strip().lower() for tok in REGEX.split(text)]

def stopwords(text):
	reg = re.compile(r"\n")
	return reg.split(text)

In [ ]:
file = open("drive/MyDrive/Tugas3TKI2/source1.txt","r");
raw1 = file.read()

file = open("drive/MyDrive/Tugas3TKI2/source2.txt","r");
raw2 = file.read()

file = open("drive/MyDrive/Tugas3TKI2/source3.txt","r");
raw3 = file.read()

file = open("drive/MyDrive/Tugas3TKI2/source4.txt","r");
raw4 = file.read()

file = open("drive/MyDrive/Tugas3TKI2/source5.txt","r");
raw5 = file.read()

In [ ]:
# menghilangkan tanda baca
tandabaca = [".",",","-","%"]
for td in tandabaca:
	raw1=raw1.replace(td,"")
	raw2=raw2.replace(td,"")
	raw3=raw3.replace(td,"")
	raw4=raw4.replace(td,"")
	raw5=raw5.replace(td,"")

In [ ]:
# menghilangkan stop words
file = open("drive/MyDrive/Tugas3TKI/stopwords.txt","r");
st = file.read()
stopwords = stopwords(st)

for word in stopwords:
	raw1=raw1.replace(" "+word+" "," ")
	raw2=raw2.replace(" "+word+" "," ")
	raw3=raw3.replace(" "+word+" "," ")
	raw4=raw4.replace(" "+word+" "," ")
	raw5=raw5.replace(" "+word+" "," ")

In [ ]:
# stemming 
factory = StemmerFactory()
stemmer = factory.create_stemmer()


hasilstem1 = stemmer.stem(raw1)
hasilstem2 = stemmer.stem(raw2)
hasilstem3 = stemmer.stem(raw3)
hasilstem4 = stemmer.stem(raw4)
hasilstem5 = stemmer.stem(raw5)

In [ ]:
#tokenization
train_set = [hasilstem1,hasilstem2,hasilstem3,hasilstem4,hasilstem5]

In [ ]:
count_vectorizer = CountVectorizer(tokenizer=tokenize)
data = count_vectorizer.fit_transform(train_set).toarray()
vocab = count_vectorizer.get_feature_names_out()

/usr/local/lib/python3.9/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [ ]:
print ("Jumlah Term FREQUENCY=============================")
print (data)

Jumlah Term FREQUENCY=============================
[[0 1 0 ... 3 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 1 0 4]
 [0 1 1 ... 0 0 0]
 [1 1 0 ... 0 1 0]]


In [ ]:
print ("VECTOR FITUR=============================")
print (vocab)

VECTOR FITUR=============================
['2022' '2023' '21' '23' '230323' '25' '3' '7' '99' 'acara' 'acu' 'ada'
 'adapun' 'agustus' 'aisha' 'ajar' 'akselerasi' 'akun' 'alam' 'alami'
 'aldiano' 'alfian' 'alih' 'and' 'andi' 'angkasa' 'anjing' 'anjur' 'antar'
 'anti' 'antibodi' 'apa' 'api' 'ardianto' 'asn' 'awat' 'bagi' 'bagus'
 'bahagia' 'baik' 'bakar' 'bal' 'banding' 'bantu' 'barang' 'bas' 'batas'
 'baterai' 'bayar' 'bbm' 'beber' 'beda' 'beli' 'belum' 'benarbenar'
 'beramahtamah' 'berapa' 'berita' 'bernardi' 'bersamasama' 'biaya'
 'bilang' 'bising' 'boleh' 'bolehboleh' 'buah' 'buahbuahan' 'buang' 'buka'
 'bukber' 'busana' 'cabut' 'cegah' 'cepat' 'combustion' 'contoh' 'corona'
 'covid19' 'cuit' 'curi' 'daerah' 'dalam' 'dan' 'dara' 'data' 'dengan'
 'denpasar' 'deret' 'detikcom' 'di' 'dia' 'direktur' 'ditreskrimum'
 'djumiril' 'doctor' 'dokter' 'dorong' 'dr' 'dua' 'efisien' 'ekor'
 'embelembel' 'emisi' 'empat' 'end' 'energi' 'engine' 'entertaimet'
 'fajar' 'fakultas' 'februari' 'fkm' 'fo

In [ ]:
print ("JUMLAH VECTOR FITUR=============================")
print (len(vocab))

JUMLAH VECTOR FITUR=============================
390


In [ ]:
tfidf = TfidfVectorizer().fit_transform(train_set)
pairwise_similarity = tfidf * tfidf.T

In [ ]:
print ("Jumlah Term FREQUENCY-Inverse Document Frequency=============================")
print (tfidf)

Jumlah Term FREQUENCY-Inverse Document Frequency=============================
  (0, 279)	0.04491504769540274
  (0, 325)	0.04491504769540274
  (0, 133)	0.030080130906393384
  (0, 270)	0.04491504769540274
  (0, 13)	0.04491504769540274
  (0, 324)	0.04491504769540274
  (0, 153)	0.04491504769540274
  (0, 316)	0.13474514308620822
  (0, 142)	0.04491504769540274
  (0, 169)	0.04491504769540274
  (0, 176)	0.04491504769540274
  (0, 342)	0.03623717767251356
  (0, 230)	0.03623717767251356
  (0, 213)	0.03623717767251356
  (0, 3)	0.03623717767251356
  (0, 162)	0.04491504769540274
  (0, 161)	0.07247435534502712
  (0, 254)	0.04491504769540274
  (0, 80)	0.08983009539080548
  (0, 35)	0.08983009539080548
  (0, 25)	0.04491504769540274
  (0, 349)	0.04491504769540274
  (0, 115)	0.13474514308620822
  (0, 17)	0.04491504769540274
  (0, 252)	0.04491504769540274
  :	:
  (4, 88)	0.03787417908631801
  (4, 143)	0.03787417908631801
  (4, 366)	0.07574835817263602
  (4, 276)	0.03787417908631801
  (4, 309)	0.03143898995

In [ ]:
print ("Jumlah COSINE-SIMILARITY=============================")
print (pairwise_similarity)

Jumlah COSINE-SIMILARITY=============================
  (0, 1)	0.049606635674658874
  (0, 2)	0.032518514114530064
  (0, 4)	0.056230467372605855
  (0, 3)	0.029625807695633583
  (0, 0)	0.9999999999999989
  (1, 2)	0.0016383370139384085
  (1, 4)	0.0031343163289590356
  (1, 3)	0.002954003239845324
  (1, 0)	0.049606635674658874
  (1, 1)	0.9999999999999999
  (2, 1)	0.0016383370139384085
  (2, 0)	0.032518514114530064
  (2, 4)	0.02591909205718982
  (2, 3)	0.17858610180745066
  (2, 2)	0.9999999999999997
  (3, 1)	0.002954003239845324
  (3, 0)	0.029625807695633583
  (3, 2)	0.17858610180745066
  (3, 4)	0.011673977599406173
  (3, 3)	0.9999999999999996
  (4, 1)	0.0031343163289590356
  (4, 0)	0.056230467372605855
  (4, 2)	0.02591909205718982
  (4, 3)	0.011673977599406173
  (4, 4)	0.9999999999999996


**kesimpulan** **:** 

Cosine similarity adalah metode yang digunakan untuk mengukur seberapa mirip dua vektor atau dokumen dalam ruang vektor.
menggunakan numpy dan scikit-learn untuk menghitung cosine similarity antara dua vektor dan antara beberapa dokumen. Kita menggunakan CountVectorizer dari scikit-learn untuk mengubah dokumen menjadi representasi vektor dan kemudian menghitung cosine similarity antara setiap pasangan dokumen menggunakan cosine_similarity dari scikit-learn.

Cosine similarity biasanya digunakan dalam NLP untuk mengukur kesamaan antara dokumen, kata, atau frasa dalam ruang vektor. Semakin tinggi nilai cosine similarity, semakin mirip dokumen atau kata-kata tersebut.

Melakukan uji coba cosinus similarity menggunakan Python, untuk menguji kemampuan dan keakuratan perhitungan cosinus similarity dalam membandingkan kedekatan antara dua atau lebih dokumen. Dengan melakukan uji coba, mahasiswa dapat memahami konsep dan cara kerja perhitungan cosinus similarity secara praktis, serta mengevaluasi performa dan akurasi dari implementasi yang dilakukan. dan memperkenalkan berbagai library pendukung yang dapat digunakan untuk mengimplementasikan metode temu kembali informasi, seperti Pandas, Scikit-learn, dan NLTK.

